sitename: Smokefree Library
sitelogo: /assets/images/logo-black.png
sitelogo-small: /assets/images/logo-white.png
sitedomain: oursite.gov
siteemail: info@oursite.gov
sitephone: 800-555-1GOV
agencycontent: Agency Contact Center
parentagency: Parent Agency
parentshortname: PA
parentsite: theirsite.gov
parentlogo: /assets/images/parent-sample-logo.svg